-- =====================================================================
-- MultiVault — Billing catalog seed
-- Applied after V1. Ids are auto-generated by gen_random_uuid() (V1 PK
-- default); plans are looked up by code at runtime.
-- max_users caps active tenant_members per tenant. Enforcement is pending
-- (no trigger on tenant_usage yet), see docs/02-Backend/Servicios.md.
-- =====================================================================

INSERT INTO plan (code, name, price_cents, max_storage_bytes, max_users, max_requests_per_minute, is_active)
VALUES
    ('FREE',       'Free',       0,              1073741824,     3,   60,   true),
    ('PRO',        'Pro',        1900,           107374182400,   10,  1000, true),
    ('BUSINESS',   'Business',   7900,           536870912000,   100, 3000, true),
    ('ENTERPRISE', 'Enterprise', 19900,          1099511627776,  500, 6000, true);
